### ISSUE TITLE
Transcode non-ASCII &str to UTF-16 in `nsstring!` macro

### ISSUE THREAD

**Issue by nvzqz** [nvzqz/fruity#3]
In Objective-C, `NSString` literals (e.g. `@"string"`) with unicode data are represented as UTF-16. This crate currently does not transcode non-ASCII `&str` data to UTF-16 and instead incorrectly emits UTF-8 data.

Correct behavior would be to have the pointer refer to UTF-16 data with `0x7D0` as the flags.

These flags are 7 for the `CFTypeID` and `D0` for (from `CFString.c` source):

> !!! Note: Constant CFStrings use the bit patterns:
> C8 (11001000 = default allocator, not inline, not freed contents; 8-bit; has NULL byte; doesn't have length; is immutable)
> D0 (11010000 = default allocator, not inline, not freed contents; Unicode; is immutable)
> The bit usages should not be modified in a way that would effect these bit patterns.

**Comment by thomcc** [comment]
So, you managed to nerd-snipe me into this, but actually integrating it into the `nsstring!` macro is too much of a hassle. Mostly because of non-encoding stuff the macro needs to do, such as:

- Forbid NULs in the input unless it's at the end of the input.
- Automatically append a NUL to the end of the input, but only if it wasn't given.
- Use the current code for ASCII.
- Use the right NSString flags, admittedly this one is not bad.
- ...

And so, my motivation to keep pushing is dwindling (had other code I wanted to write today) and so here's a playground link that defines a `utf16_lit!` macro (including tests for it and the encoding helpers):

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d4bf36ff8d49186c4a299a81e67c1d01

Notes on implementation:

- It's annoying you can't do &s[i..] inside `const fn`. It just passes indices around as a result.
- It will panic for most invalid UTF-8, and probably just spit out garbage for the rest. If you give it a bad index it should panic though.

---

If you use it, you should give me and @rodrimati1992 (who wrote the macro part and skeleton code for using an iterator like this) coauthored-by lines on the commit for it, e.g. end the commit message with:

```
Co-authored-by: Nikolai Vazquez <hello@nikolaivazquez.com>
Co-authored-by: Thom Chiovoloni <chiovolonit@gmail.com>
Co-authored-by: rodrimati1992 <rodrimatt1985@gmail.com>
```

**Comment by nvzqz** [comment]
Thanks a ton for your implementation @thomcc! This also enables the string to contain interior nulls, which is a cool bonus feature.
